---
- name: Install Gnome customisation packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnome-shell-extensions
    - gnome-tweaks
  when: gnome_desktop_classic_alttab

- name: Enable alternate-tab
  become: false
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['alternate-tab@gnome-shell-extensions.gcampax.github.com']"
  when: gnome_desktop_classic_alttab

