---
- name: Install Gnome customisation packages
  become: true
  apt:
    pkg:
      - gnome-shell-extensions
      - gnome-tweaks
    state: present
  when: gnome_desktop_classic_alttab

- name: Enable alternate-tab
  become: false
  dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['alternate-tab@gnome-shell-extensions.gcampax.github.com']"
  when: gnome_desktop_classic_alttab

