---
- name: Disable Native Scroll for Mouse
  become: false
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/natural-scroll"
    value: "false"
  when: gnome_desktop_disable_native_scroll

- name: Disable Native Scroll for Touchpad
  become: false
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
    value: "false"
  when: gnome_desktop_disable_native_scroll

